# Generated by Django 4.2.8 on 2025-04-29 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(default="No Message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="firstName",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces, hyphens, or apostrophes.",
                        regex="^[A-Za-zÀ-ÿ' -]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="lastName",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces, hyphens, or apostrophes.",
                        regex="^[A-Za-zÀ-ÿ' -]+$",
                    )
                ],
            ),
        ),
    ]
