# Generated by Django 4.2.20 on 2025-05-01 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contact_message_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("date", models.CharField(max_length=30)),
                ("blurb", models.TextField(default=" ")),
                ("link", models.URLField()),
                ("icon", models.ImageField(upload_to="")),
                ("tech", models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="firstName",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters used.", regex="^[A-Za-zÀ-ÿ' -]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="lastName",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters used.", regex="^[A-Za-zÀ-ÿ' -]+$"
                    )
                ],
            ),
        ),
    ]
