# Generated by Django 4.2.20 on 2025-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_projects_alter_contact_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="icon",
            field=models.ImageField(upload_to="icons"),
        ),
    ]
