version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/images:/app/images
    env_file:
      - ./backend/.env
  nginx:
    build:
      context: ./backend
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/images:/app/images
      - /etc/letsencrypt:/etc/letsencrypt


volumes:
  static_volume:
