name: CI/CD Workflow

on:
  push:
    branches:
      - main 
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -f backend/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/portfolio-backend ./backend
        docker build -f backend/nginx/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend ./backend/nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/portfolio
          git pull origin main
          docker compose down
          docker compose up -d --build
          
    - name: Run collectstatic
      run: |
        docker-compose exec -T web python manage.py collectstatic --noinput
